Repository DO-SOPT-APP3-Airbnb/Airbnb-Android, pull requests merged in 2023-12, with the labels that each got.

#16 [Feature/#14] : where api, when detail
  app/src/main/java/com/example/airbnb/data/api/ExampleApiService.kt
  app/src/main/java/com/example/airbnb/data/dto/BaseResponse.kt
  app/src/main/java/com/example/airbnb/data/dto/response/ResponseNickNameDto.kt
  app/src/main/java/com/example/airbnb/presentation/ExampleViewModel.kt
  app/src/main/java/com/example/airbnb/presentation/MainActivity.kt
  app/src/main/java/com/example/airbnb/presentation/when/CalenderAdapter.kt
  app/src/main/java/com/example/airbnb/presentation/when/WhenActivity.kt
  app/src/main/java/com/example/airbnb/presentation/when/WhenViewModel.kt
  app/src/main/java/com/example/airbnb/presentation/when/viewholder/CalenderViewHolder.kt
  app/src/main/res/layout/activity_when.xml
  app/src/main/res/layout/view_calender_selection.xml
Labels: 💟 [UI], ⭐ [FEAT], 🐈‍⬛ 소현

#17 [Feature/#12] Where API 구현
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/airbnb/data/ApiFactory.kt
  app/src/main/java/com/example/airbnb/data/api/WhereApiService.kt
  app/src/main/java/com/example/airbnb/data/dto/BaseResponse.kt
  app/src/main/java/com/example/airbnb/data/dto/response/ResponseWhereDto.kt
  app/src/main/java/com/example/airbnb/presentation/where/WhereActivity.kt
  app/src/main/java/com/example/airbnb/presentation/where/WhereItem.kt
  app/src/main/java/com/example/airbnb/presentation/where/WherePagerAdapter.kt
  app/src/main/java/com/example/airbnb/presentation/where/WhereViewHolder.kt
  app/src/main/java/com/example/airbnb/presentation/where/WhereViewModel.kt
  app/src/main/java/com/example/airbnb/presentation/who/WhoActivity.kt
  app/src/main/res/layout/activity_where.xml
  app/src/main/res/layout/activity_who.xml
  app/src/main/res/layout/item_where_location.xml
  app/src/main/res/layout/view_appbar.xml
Labels: ⭐ [FEAT], 🍋 언지

#19 Feature/#18 where nickname
  app/src/main/java/com/example/airbnb/core/base/BindingActivity.kt
  app/src/main/java/com/example/airbnb/data/ApiFactory.kt
  app/src/main/java/com/example/airbnb/data/api/ExampleApiService.kt
  app/src/main/java/com/example/airbnb/data/api/WhereApiService.kt
  app/src/main/java/com/example/airbnb/data/dto/BaseResponse.kt
  app/src/main/java/com/example/airbnb/presentation/ExampleViewModel.kt
  app/src/main/java/com/example/airbnb/presentation/where/WhereActivity.kt
  app/src/main/java/com/example/airbnb/presentation/where/WherePagerAdapter.kt
  app/src/main/java/com/example/airbnb/presentation/where/WhereViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_where.xml
  app/src/main/res/layout/view_appbar.xml
Labels: 🐈‍⬛ 소현,  ♻️ [REFACTOR]
