Repository DO-SOPT-APP3-Airbnb/Airbnb-Android, pull requests merged in 2023-11, with the labels that each got.

#10 [ADD/#9] : api setting
  app/build.gradle
  app/src/main/java/com/example/airbnb/data/ApiFactory.kt
  app/src/main/java/com/example/airbnb/data/dto/BaseResponse.kt
Labels: ➕ [ADD], 🐈‍⬛ 소현

#6 [UI/#4] : Explore view, 기본 로직 구현
  .idea/encodings.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/airbnb/data/DummyExploreImageList.kt
  app/src/main/java/com/example/airbnb/data/ExploreImage.kt
  app/src/main/java/com/example/airbnb/presentation/MainActivity.kt
  app/src/main/java/com/example/airbnb/presentation/explore/ExploreFragment.kt
  app/src/main/java/com/example/airbnb/presentation/explore/ExploreViewPagerAdapter.kt
  app/src/main/res/color/bnv_item_selector.xml
  app/src/main/res/color/tab_item_selector.xml
  app/src/main/res/drawable/ex_good1.png
  app/src/main/res/drawable/ex_good2.png
  app/src/main/res/drawable/ex_room1.png
  app/src/main/res/drawable/ex_room2.png
  app/src/main/res/drawable/ex_sea1.png
  app/src/main/res/drawable/ex_sea2.png
  app/src/main/res/drawable/ex_tree1.png
  app/src/main/res/drawable/ex_tree2.png
  app/src/main/res/drawable/explore_favorite_selector.xml
  app/src/main/res/drawable/ic_explore_favorite_default.xml
  app/src/main/res/drawable/ic_explore_favorite_selected.xml
  app/src/main/res/drawable/ic_explore_filtering.xml
  app/src/main/res/drawable/ic_explore_goodview.xml
  app/src/main/res/drawable/ic_explore_map.xml
  app/src/main/res/drawable/ic_explore_room.xml
  app/src/main/res/drawable/ic_explore_search.xml
  app/src/main/res/drawable/ic_explore_seashore.xml
  app/src/main/res/drawable/ic_explore_star.xml
  app/src/main/res/drawable/ic_explore_treehouse.xml
  app/src/main/res/drawable/ic_main_message_bnv_menu_default.xml
  app/src/main/res/drawable/ic_main_profile_bnv_menu_default.xml
  app/src/main/res/drawable/ic_main_search_bnv_menu_default.xml
  app/src/main/res/drawable/ic_main_trip_bnv_menu_default.xml
  app/src/main/res/drawable/ic_main_wishlist_bnv_menu_default.xml
  app/src/main/res/drawable/shape_black_fill_rec.xml
  app/src/main/res/drawable/shape_gray_fill_14_rect_image_loading.xml
  app/src/main/res/drawable/shape_white_fill_29_rect_search_bar.xml
  app/src/main/res/drawable/shape_white_line_14_rect.xml
  app/src/main/res/drawable/shape_white_line_30_rect.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/item_explore_viewpage.xml
  app/src/main/res/menu/menu_bot_nav.xml
  app/src/main/res/menu/menu_top_nav.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🍒 유리, 💟 [UI], ⭐ [FEAT]

#7 [UI/#5] : Where&Who view, 기본 로직 구현
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/example/airbnb/presentation/where/WhereActivity.kt
  app/src/main/java/com/example/airbnb/presentation/where/WhereItem.kt
  app/src/main/java/com/example/airbnb/presentation/where/WherePagerAdapter.kt
  app/src/main/java/com/example/airbnb/presentation/who/WhoActivity.kt
  app/src/main/java/com/example/airbnb/presentation/who/WhoViewModel.kt
  app/src/main/res/drawable/ic_where_progress_bar.xml
  app/src/main/res/drawable/ic_who_count_decrease.xml
  app/src/main/res/drawable/ic_who_count_increase.xml
  app/src/main/res/drawable/ic_who_progress_bar.xml
  app/src/main/res/drawable/img_where_background.png
  app/src/main/res/drawable/img_where_map_world_test.png
  app/src/main/res/drawable/img_who_background.png
  app/src/main/res/drawable/sel_where_tab_item.xml
  app/src/main/res/drawable/shape_gray1_fill_circle.xml
  app/src/main/res/drawable/shape_gray_icon_fill_top10_rect.xml
  app/src/main/res/drawable/shape_main1_fill_top10_rect.xml
  app/src/main/res/drawable/shape_white_40_fill_20_rect.xml
  app/src/main/res/drawable/shape_white_40_fill_bot10_rect.xml
  app/src/main/res/drawable/shape_white_fill_circle.xml
  app/src/main/res/layout/activity_where.xml
  app/src/main/res/layout/activity_who.xml
  app/src/main/res/layout/item_where_location.xml
  app/src/main/res/layout/item_who_count.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 💟 [UI], ⭐ [FEAT], 🍋 언지

#8 [UI/#3] when UI 구현, 데이터 넣기
  app/src/main/java/com/example/airbnb/presentation/when/CalenderAdapter.kt
  app/src/main/java/com/example/airbnb/presentation/when/SelectDateAdapter.kt
  app/src/main/java/com/example/airbnb/presentation/when/WhenActivity.kt
  app/src/main/java/com/example/airbnb/presentation/when/viewholder/CalenderViewHolder.kt
  app/src/main/java/com/example/airbnb/presentation/when/viewholder/SelectDateViewHolder.kt
  app/src/main/java/com/example/airbnb/presentation/when/viewholder/SelectExactDateViewHolder.kt
  app/src/main/res/drawable-xhdpi/img_when_background.png
  app/src/main/res/drawable-xxhdpi/img_when_background.png
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_when_plus_minus.xml
  app/src/main/res/drawable/ic_when_progressbar.xml
  app/src/main/res/drawable/img_when_background.png
  app/src/main/res/drawable/sel_when_calender_date.xml
  app/src/main/res/drawable/sel_when_date.xml
  app/src/main/res/drawable/sel_when_drawable_calender_selection_switch.xml
  app/src/main/res/drawable/sel_when_drawable_calender_selection_thumb.xml
  app/src/main/res/drawable/sel_when_exact_date.xml
  app/src/main/res/drawable/sel_when_exact_date_text.xml
  app/src/main/res/drawable/shape_black1_fill_10_rec.xml
  app/src/main/res/drawable/shape_black1_fill_20_rec.xml
  app/src/main/res/drawable/shape_black1_fill_24_rec.xml
  app/src/main/res/drawable/shape_gray_fill_20_rec.xml
  app/src/main/res/drawable/shape_white_40_fill_20_rec.xml
  app/src/main/res/drawable/shape_white_40_fill_black1_line_20_rec.xml
  app/src/main/res/drawable/shape_white_40_fill_gray_line_20_rec.xml
  app/src/main/res/drawable/shape_white_fill_gray_line_20_rec.xml
  app/src/main/res/drawable/shape_white_fill_gray_line_20_size_rec.xml
  app/src/main/res/layout/activity_when.xml
  app/src/main/res/layout/item_calender_date.xml
  app/src/main/res/layout/item_when_select_date.xml
  app/src/main/res/layout/item_when_select_exact_date.xml
  app/src/main/res/layout/view_appbar.xml
  app/src/main/res/layout/view_calender_selection.xml
  app/src/main/res/layout/view_calender_week.xml
  app/src/main/res/values/strings.xml
Labels: 💟 [UI], ⭐ [FEAT], 🐈‍⬛ 소현
